codecov:
  branch: master
  token: edd2feb9-70ff-42cf-9a56-65a49fe4f727
coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:    
    gitter:
      default:
        url: https://gitter.im/salon-cloud/Lobby
        threshold: null
        branches: master
        message: null 

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: master
  behavior: default
